### ISSUE TITLE
Running VADA with feature vectors (1D instead of 2D)

### ISSUE THREAD

**Issue by MattiasM80** [RuiShu/dirt-t#2]
Hello,
The paper refers to a test using Wifi data. I assume that this Wifi data appears like a 1 dimensional feature vector and I want to ask if there is some runtime flags that one can raise in order for the code to accept image features rather than full images as train/test data?  

Thanks
Mattias

**Comment by RuiShu** [comment]
Hiro did the Wifi experiments; you can ping him at hirokaz2 (@stanford.edu) for further inquiries. This code as written in this repo only accepts rank 4 tensors (NHWC). Feel free to fork+modify the code though :)
